// ВиниловыйМир — Vinyl Records Store Data
// Complete catalog of vinyl records

const records = [
  {
    id: 'vm-001',
    catalogNum: 'VM-001',
    title: 'Kind of Blue',
    artist: 'Miles Davis',
    year: 1959,
    genre: 'Джаз',
    subgenre: 'Modal Jazz',
    price: 4200,
    condition: 'Near Mint',
    format: 'LP',
    label: 'Columbia Records',
    country: 'США',
    description: 'Одна из самых продаваемых джазовых пластинок всех времён. Переиздание 2015 года на 180-граммовом виниле с оригинальным мастерингом.',
    tracklist: [
      { side: 'A', number: 1, title: 'So What', duration: '9:22' },
      { side: 'A', number: 2, title: 'Freddie Freeloader', duration: '9:46' },
      { side: 'A', number: 3, title: 'Blue in Green', duration: '5:37' },
      { side: 'B', number: 1, title: 'All Blues', duration: '11:33' },
      { side: 'B', number: 2, title: 'Flamenco Sketches', duration: '9:26' },
    ],
    featured: true,
    inStock: 3,
  },
  {
    id: 'vm-002',
    catalogNum: 'VM-002',
    title: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    year: 1973,
    genre: 'Рок',
    subgenre: 'Progressive Rock',
    price: 5800,
    condition: 'Mint',
    format: 'LP',
    label: 'Harvest Records',
    country: 'Великобритания',
    description: 'Легендарный альбом прогрессивного рока. Юбилейное издание 50th Anniversary на 180-граммовом виниле.',
    tracklist: [
      { side: 'A', number: 1, title: 'Speak to Me / Breathe', duration: '3:57' },
      { side: 'A', number: 2, title: 'On the Run', duration: '3:30' },
      { side: 'A', number: 3, title: 'Time', duration: '7:05' },
      { side: 'A', number: 4, title: 'The Great Gig in the Sky', duration: '4:44' },
      { side: 'B', number: 1, title: 'Money', duration: '6:22' },
      { side: 'B', number: 2, title: 'Us and Them', duration: '7:49' },
      { side: 'B', number: 3, title: 'Any Colour You Like', duration: '3:26' },
      { side: 'B', number: 4, title: 'Brain Damage', duration: '3:49' },
      { side: 'B', number: 5, title: 'Eclipse', duration: '2:03' },
    ],
    featured: true,
    inStock: 2,
  },
  {
    id: 'vm-003',
    catalogNum: 'VM-003',
    title: 'Blue Train',
    artist: 'John Coltrane',
    year: 1957,
    genre: 'Джаз',
    subgenre: 'Hard Bop',
    price: 3900,
    condition: 'Near Mint',
    format: 'LP',
    label: 'Blue Note Records',
    country: 'США',
    description: 'Единственный альбом Колтрейна для Blue Note. Переиздание Blue Note Classic Vinyl Series на 180-граммовом виниле.',
    tracklist: [
      { side: 'A', number: 1, title: 'Blue Train', duration: '10:40' },
      { side: 'A', number: 2, title: 'Moment\'s Notice', duration: '8:36' },
      { side: 'B', number: 1, title: 'Locomotion', duration: '7:13' },
      { side: 'B', number: 2, title: 'I\'m Old Fashioned', duration: '7:55' },
      { side: 'B', number: 3, title: 'Lazy Bird', duration: '7:04' },
    ],
    featured: false,
    inStock: 2,
  },
  {
    id: 'vm-004',
    catalogNum: 'VM-004',
    title: 'Abbey Road',
    artist: 'The Beatles',
    year: 1969,
    genre: 'Рок',
    subgenre: 'Rock / Pop',
    price: 4500,
    condition: 'Very Good+',
    format: 'LP',
    label: 'Apple Records',
    country: 'Великобритания',
    description: 'Последний альбом The Beatles, записанный в студии Abbey Road. Переиздание 2012 года на 180-граммовом виниле.',
    tracklist: [
      { side: 'A', number: 1, title: 'Come Together', duration: '4:19' },
      { side: 'A', number: 2, title: 'Something', duration: '3:03' },
      { side: 'A', number: 3, title: 'Maxwell\'s Silver Hammer', duration: '3:27' },
      { side: 'A', number: 4, title: 'Oh! Darling', duration: '3:26' },
      { side: 'A', number: 5, title: 'Octopus\'s Garden', duration: '2:51' },
      { side: 'B', number: 1, title: 'I Want You (She\'s So Heavy)', duration: '7:47' },
      { side: 'B', number: 2, title: 'Here Comes the Sun', duration: '3:05' },
      { side: 'B', number: 3, title: 'Because', duration: '2:45' },
      { side: 'B', number: 4, title: 'You Never Give Me Your Money', duration: '4:02' },
      { side: 'B', number: 5, title: 'Sun King', duration: '2:26' },
      { side: 'B', number: 6, title: 'Mean Mr. Mustard', duration: '1:09' },
      { side: 'B', number: 7, title: 'Polythene Pam', duration: '1:12' },
      { side: 'B', number: 8, title: 'She Came in Through the Bathroom Window', duration: '1:57' },
      { side: 'B', number: 9, title: 'Golden Slumbers', duration: '1:31' },
      { side: 'B', number: 10, title: 'Carry That Weight', duration: '1:36' },
      { side: 'B', number: 11, title: 'The End', duration: '2:20' },
    ],
    featured: true,
    inStock: 4,
  },
  {
    id: 'vm-005',
    catalogNum: 'VM-005',
    title: 'Autobahn',
    artist: 'Kraftwerk',
    year: 1974,
    genre: 'Электроника',
    subgenre: 'Krautrock / Synth',
    price: 5200,
    condition: 'Near Mint',
    format: 'LP',
    label: 'Kling Klang / Parlophone',
    country: 'Германия',
    description: 'Пионерский альбом электронной музыки. Ремастированное издание 2020 года.',
    tracklist: [
      { side: 'A', number: 1, title: 'Autobahn', duration: '22:43' },
      { side: 'B', number: 1, title: 'Kometenmelodie 1', duration: '6:49' },
      { side: 'B', number: 2, title: 'Kometenmelodie 2', duration: '6:49' },
      { side: 'B', number: 3, title: 'Mitternacht', duration: '4:28' },
      { side: 'B', number: 4, title: 'Morgenspaziergang', duration: '4:14' },
    ],
    featured: false,
    inStock: 2,
  },
  {
    id: 'vm-006',
    catalogNum: 'VM-006',
    title: 'Goldberg Variations',
    artist: 'Glenn Gould',
    year: 1981,
    genre: 'Классика',
    subgenre: 'Барокко / Фортепиано',
    price: 6800,
    condition: 'Mint',
    format: 'LP',
    label: 'CBS Masterworks',
    country: 'Канада',
    description: 'Легендарная запись Гульда 1981 года — его последняя студийная работа. Переиздание на 180-граммовом виниле.',
    tracklist: [
      { side: 'A', number: 1, title: 'Aria', duration: '3:02' },
      { side: 'A', number: 2, title: 'Variatio 1-15', duration: '22:00' },
      { side: 'B', number: 1, title: 'Variatio 16-30', duration: '21:00' },
      { side: 'B', number: 2, title: 'Aria da Capo', duration: '3:02' },
    ],
    featured: true,
    inStock: 1,
  },
  {
    id: 'vm-007',
    catalogNum: 'VM-007',
    title: 'Nevermind',
    artist: 'Nirvana',
    year: 1991,
    genre: 'Рок',
    subgenre: 'Grunge',
    price: 4100,
    condition: 'Mint',
    format: 'LP',
    label: 'DGC Records',
    country: 'США',
    description: 'Альбом, изменивший рок-музыку. 30th Anniversary Edition на 180-граммовом виниле.',
    tracklist: [
      { side: 'A', number: 1, title: 'Smells Like Teen Spirit', duration: '5:01' },
      { side: 'A', number: 2, title: 'In Bloom', duration: '4:14' },
      { side: 'A', number: 3, title: 'Come as You Are', duration: '3:38' },
      { side: 'A', number: 4, title: 'Breed', duration: '3:03' },
      { side: 'A', number: 5, title: 'Lithium', duration: '4:17' },
      { side: 'B', number: 1, title: 'Polly', duration: '2:57' },
      { side: 'B', number: 2, title: 'Territorial Pissings', duration: '2:22' },
      { side: 'B', number: 3, title: 'Drain You', duration: '3:43' },
      { side: 'B', number: 4, title: 'Lounge Act', duration: '2:36' },
      { side: 'B', number: 5, title: 'Stay Away', duration: '3:32' },
      { side: 'B', number: 6, title: 'On a Plain', duration: '3:16' },
      { side: 'B', number: 7, title: 'Something in the Way', duration: '3:52' },
    ],
    featured: false,
    inStock: 6,
  },
  {
    id: 'vm-008',
    catalogNum: 'VM-008',
    title: 'Selected Ambient Works 85–92',
    artist: 'Aphex Twin',
    year: 1992,
    genre: 'Электроника',
    subgenre: 'Ambient Techno',
    price: 5500,
    condition: 'Near Mint',
    format: 'LP',
    label: 'Apollo / R&S Records',
    country: 'Великобритания',
    description: 'Основополагающий альбом эмбиент-техно. Двойной LP на 180-граммовом виниле.',
    tracklist: [
      { side: 'A', number: 1, title: 'Xtal', duration: '4:54' },
      { side: 'A', number: 2, title: 'Tha', duration: '9:03' },
      { side: 'A', number: 3, title: 'Pulsewidth', duration: '3:45' },
      { side: 'B', number: 1, title: 'Ageispolis', duration: '5:22' },
      { side: 'B', number: 2, title: 'i', duration: '1:13' },
      { side: 'B', number: 3, title: 'Green Calx', duration: '6:34' },
      { side: 'C', number: 1, title: 'Heliosphan', duration: '4:51' },
      { side: 'C', number: 2, title: 'We Are the Music Makers', duration: '7:42' },
      { side: 'D', number: 1, title: 'Schottkey 7th Path', duration: '5:07' },
      { side: 'D', number: 2, title: 'Ptolemy', duration: '7:13' },
      { side: 'D', number: 3, title: 'Hedphelym', duration: '5:36' },
    ],
    featured: false,
    inStock: 3,
  },
];

const genres = ['Все', 'Джаз', 'Рок', 'Классика', 'Электроника'];

const teamMembers = [
  {
    name: 'Александр Громов',
    role: 'Основатель и куратор',
    bio: 'Коллекционирует винил более 20 лет. Специализируется на джазе и классике.',
    initials: 'АГ',
  },
  {
    name: 'Елена Соколова',
    role: 'Музыкальный эксперт',
    bio: 'Музыковед, специалист по электронной музыке и экспериментальному звуку.',
    initials: 'ЕС',
  },
  {
    name: 'Дмитрий Ларин',
    role: 'Технический специалист',
    bio: 'Отвечает за качество пластинок и обслуживание проигрывателей.',
    initials: 'ДЛ',
  },
];
